from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

Severity = Literal["error", "warning"]

ALLOWED_MANIFEST_FIELDS = {
    "activity_type_id",
    "activity_id",
    "name",
    "description",
    "model",
    # Optional graph-specific model override (e.g. memory-archive uses
    # qwen-plus for relation-graph extraction while keeping deepseek
    # for chat). Same "<provider>:<model_id>" format as ``model``.
    "graph_model",
    "skill_sources",
    "entrypoint",
    "input_modes",
    "capabilities",
    # Static Preview model: an activity opts in by declaring one or both;
    # runtime then loads
    # activities/<id>/<tools_module>.py and activities/<id>/<dsl_builder_module>.py
    # and exposes the in-process @tool surface + DSL-driven preview at
    # /preview/<activity_type_id>/<activity_id>/.
    "tools_module",
    "dsl_builder_module",
    # Handler-first architecture (plan §25): activity exposes pure
    # business functions via this module; @tools wrap them and the SPA
    # reaches them via POST /preview/<activity_type_id>/<activity_id>/api/<handler_name>.
    "handlers_module",
    # Catalog metadata for Go's activity-type sync (GET /v1/activity-types).
    "enabled",
    "sort_order",
    # Provider/runtime secrets the activity's sandboxed code may read from its
    # environment (validated as ^[A-Z][A-Z0-9_]*$). See app/models.py
    # ActivityManifest.sandbox_env + validate_sandbox_env.
    "sandbox_env",
}
ALLOWED_CAPABILITIES = {"image_generate", "image_edit", "tts_generate", "read_document"}
ALLOWED_RUNTIME_FIELDS = {
    "llm_timeout_seconds",
    "llm_max_output_tokens",
    "docker_timeout_seconds",
    "max_distinct_support_reads",
    "data_schema_enabled",
    # SSE debug view config — see app/models.py SseDebugViewConfig.
    # THIS package module is the canonical whitelist; the repo-root
    # tools/activity_verifier.py re-exports it (not a copy). Keep this set in
    # sync with app/models.py ActivityRuntimeConfig and runtime.schema.json.
    "sse_debug_view",
    # Optional per-activity overrides for the image provider's model id.
    # Falls back to IMAGE_GEN_MODEL / IMAGE_EDIT_MODEL when unset.
    "image_generate_model",
    "image_edit_model",
    # Per-activity opt-in for the deepagents write_todos planner tool.
    # Default false; enable only for genuinely multi-step pipeline activities.
    # See app/models.py ActivityRuntimeConfig and app/deepagents_runtime.py.
    "write_todos",
    # Per-activity override for the runtime auto-memory layer (None = follow the
    # global AUTO_MEMORY_ENABLED). See app/models.py ActivityRuntimeConfig and
    # app/auto_memory.py.
    "auto_memory_enabled",
}
GENERIC_ROOTS = ("app", "frontend-src", "schemas")

# Python dependency check. An activity's Python (tools.py / dsl_builder.py /
# handlers.py + any helper modules they ship) runs inside the host's single
# shared venv — there is NO per-activity isolation (app/dev_sync.py pip-installs
# activities/<id>/requirements.txt into that same venv; the Dockerfile bakes
# every activity's requirements at build time). So any third-party package an
# activity imports must be declared in its own requirements.txt, or it will
# ImportError at runtime on a fresh host. The verifier enforces completeness:
# an import that is neither stdlib, nor in the platform baseline, nor first
# party, nor a sibling module the activity ships, nor declared in the
# activity's requirements.txt is an undeclared dependency.
#
# The baseline is the transitive closure of the host's own requirements.txt,
# generated by tools/gen-python-baseline.py. Regenerate it when the host deps
# change.
FIRST_PARTY_ROOTS = frozenset({"app"})
_PYTHON_BASELINE_PATH = Path(__file__).resolve().parent.parent / "references" / "runtime-python-baseline.txt"

# Wrong field names that LLMs and stale docs keep producing. The canonical
# field names live in app/models.py (pydantic); these are the common typos /
# look-alikes the verifier should catch in card templates so they don't reach
# StrictModel at runtime. Source: `policies/llm-output-discipline.md` +
# `references/card-block-types.md`.
WRONG_BLOCK_FIELDS = {
    "image": {
        "src": "use 'images: [{read_url, title, description}]' (pydantic ImageBlock.images)",
        "alt": "use 'images[].description'",
        "caption": "use 'images[].description'",
    },
}
WRONG_ARTIFACT_FIELDS = {
    "file_url": "use 'url' (pydantic OutputArtifact.url)",
    "byte_size": "OutputArtifact has no 'byte_size' field",
}
KNOWN_BLOCK_TYPES = {"markdown", "info", "form", "action", "image", "audio"}

# Names reserved by the runtime — activity tools.py must not register
# any @tool with one of these names or LangGraph dispatch will collide.
# Source of truth: app/activity_tools.py:BUILTIN_TOOL_NAMES. Keep them
# in sync; tests assert both lists hold the same set.
BUILTIN_TOOL_NAMES = frozenset(
    {
        # card system
        "card_emit",
        "card_emit_template",
        "card_list_templates",
        "card_retract",
        "artifact_emit",
        "artifact_retract",
        # typed-KV data store
        "data_set",
        "data_get",
        "data_append",
        "data_delete",
        "data_list_keys",
        # short-term memory
        "memory_add",
        "memory_retract",
        # turn control
        "mark_status",
        "await_user",
        "status_retract",
        # capabilities
        "image_generate",
        "image_edit",
        "tts_generate",
        # state markdown
        "state_read",
        # DeepAgents framework builtins
        "execute",
        "ls",
        "glob",
        "grep",
        "read_file",
        "write_file",
        "edit_file",
        "task",
        "write_todos",
        # reserved for future framework tools
        "manage_memory",
        "search_memory",
    }
)
NON_NATIVE_SKILL_PROMPT_HELPER = "_skill" + "_instruction" + "_text"
SKILL_MARKDOWN_PATTERN = "SKILL" + r"\.md"
FRONTEND_PRIVATE_STATE_PATTERNS = (
    re.compile(r"\binstance\s*\.\s*data\b"),
    re.compile(r"\bdata\s*\.\s*(phase|trip_brief|selected_attractions|memory_index)\b"),
)

# Doc→code tool-reference drift check. We treat a backtick-wrapped call,
# `name(`, as the unambiguous "the LLM should call this tool" signal and
# verify the name exists in tools.py. Bare backtick mentions (`name` in a
# tool-overview table or prose) are intentionally ignored — matching them would
# require parsing free-form markdown and produce far more false positives than
# real drift. See policies/tool-error-protocol.md.
_DOC_TOOL_CALL_RE = re.compile(r"`([a-z_][a-z0-9_]*)\s*\(")
# Function names that legitimately appear with call syntax in activity docs but
# are NOT activity @tools — framework entrypoints and ctx helpers the verifier
# should not flag as "missing tools".
_DOC_NON_TOOL_CALLS = frozenset({"make_tools", "build", "notify_dsl_update"})


@dataclass(frozen=True)
class VerificationIssue:
    severity: Severity
    path: str
    message: str


def verify_project(root: Path | str) -> list[VerificationIssue]:
    project_root = Path(root)
    issues: list[VerificationIssue] = []
    activity_ids = _activity_ids(project_root, issues)

    _verify_runtime_configs(project_root, issues)
    _verify_activity_contract_files(project_root, issues)
    _verify_card_template_field_names(project_root, issues)
    _verify_card_template_schema_conformance(project_root, issues)
    _verify_capabilities(project_root, issues)
    _verify_generic_runtime_references(project_root, activity_ids, issues)
    _verify_frontend_private_state_reads(project_root, issues)
    _verify_no_credential_access(project_root, issues)
    _verify_deepagents_skill_progressive_disclosure(project_root, issues)
    _verify_activity_instruction_shape(project_root, issues)
    _verify_skill_layering(project_root, issues)
    _verify_static_preview_contracts(project_root, issues)
    _verify_frontend_file_dependencies(project_root, issues)
    _verify_doc_tool_references(project_root, issues)
    _verify_python_dependencies(project_root, issues)

    return issues


def verify_activity_dir(activity_dir: Path | str, *, runtime_root: Path | str | None = None) -> list[VerificationIssue]:
    """Verify one activity directory using the canonical project-root layout.

    ``runtime_root`` is accepted for callers that run from a live runtime, but
    verification is intentionally scoped to the uploaded activity. Generic
    runtime scans belong to platform CI, not the dev-sync admission gate.
    """
    src = Path(activity_dir)
    activity_id = src.name
    manifest_path = src / "manifest.json"
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        candidate = payload.get("activity_type_id") or payload.get("activity_id")
        if isinstance(candidate, str) and candidate:
            activity_id = candidate
    except (OSError, json.JSONDecodeError):
        pass

    with tempfile.TemporaryDirectory(prefix="fda-activity-verify-") as td:
        root = Path(td)
        dst = root / "activities" / activity_id
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(src, dst)
        return verify_project(root)


def _activity_ids(root: Path, issues: list[VerificationIssue]) -> set[str]:
    ids: set[str] = set()
    for manifest_path in sorted((root / "activities").glob("*/manifest.json")):
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            issues.append(_issue("error", root, manifest_path, f"manifest.json is unreadable: {exc}"))
            continue
        for field in sorted(set(payload) - ALLOWED_MANIFEST_FIELDS):
            issues.append(_issue("error", root, manifest_path, f"manifest.json has disallowed field: {field}"))
        activity_type_id = payload.get("activity_type_id")
        legacy_activity_id = payload.get("activity_id")
        if (
            isinstance(activity_type_id, str)
            and isinstance(legacy_activity_id, str)
            and activity_type_id != legacy_activity_id
        ):
            issues.append(
                _issue(
                    "error",
                    root,
                    manifest_path,
                    "manifest.json activity_type_id and legacy activity_id must match when both are present",
                )
            )
        if activity_type_id is None and isinstance(legacy_activity_id, str) and legacy_activity_id:
            issues.append(
                _issue(
                    "warning",
                    root,
                    manifest_path,
                    "manifest.json uses deprecated activity_id; new activities should use activity_type_id",
                )
            )
        resolved_id = activity_type_id if isinstance(activity_type_id, str) and activity_type_id else legacy_activity_id
        if isinstance(resolved_id, str) and resolved_id:
            ids.add(resolved_id)
    return ids


def _verify_capabilities(root: Path, issues: list[VerificationIssue]) -> None:
    """manifest.capabilities must be a list whose entries are all in ALLOWED_CAPABILITIES."""
    for manifest_path in sorted((root / "activities").glob("*/manifest.json")):
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue  # already reported by _activity_ids
        caps = payload.get("capabilities", [])
        if not isinstance(caps, list):
            issues.append(_issue("error", root, manifest_path, "manifest.capabilities must be a list of strings"))
            continue
        for cap in caps:
            if not isinstance(cap, str) or cap not in ALLOWED_CAPABILITIES:
                issues.append(
                    _issue(
                        "error",
                        root,
                        manifest_path,
                        f"unknown capability {cap!r} (allowed: {sorted(ALLOWED_CAPABILITIES)})",
                    )
                )


def _data_schema_has_hidden_fields(data_schema_path: Path) -> bool:
    """True iff ``data.schema.json`` declares any property with
    ``x-auto-inject: false``. The runtime treats these as hidden values
    the LLM must read explicitly via ``data_get`` — and that's exactly
    the path that, if SSE debug-view is on, would surface the hidden
    value in a ``tool_completed`` payload on the chat stream. So:
    hidden fields demand an explicit SSE debug-view decision."""
    try:
        schema = json.loads(data_schema_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    if not isinstance(schema, dict):
        return False
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        return False
    for prop in properties.values():
        if isinstance(prop, dict) and prop.get("x-auto-inject") is False:
            return True
    return False


def _verify_runtime_configs(root: Path, issues: list[VerificationIssue]) -> None:
    for runtime_path in sorted((root / "activities").glob("*/runtime.json")):
        try:
            payload = json.loads(runtime_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            issues.append(_issue("error", root, runtime_path, f"runtime.json is unreadable: {exc}"))
            continue
        for field in sorted(set(payload) - ALLOWED_RUNTIME_FIELDS):
            issues.append(_issue("error", root, runtime_path, f"runtime.json has disallowed field: {field}"))
        # data_schema_enabled requires data.schema.json to exist next to runtime.json.
        data_schema_path = runtime_path.parent / "data.schema.json"
        if payload.get("data_schema_enabled") is True:
            if not data_schema_path.exists():
                issues.append(
                    _issue(
                        "error",
                        root,
                        runtime_path,
                        "runtime.json declares data_schema_enabled=true but "
                        "data.schema.json is missing in the activity directory.",
                    )
                )
        # SSE debug-view gate: activities with hidden state must declare
        # sse_debug_view explicitly in runtime.json (the value may be
        # the empty default {} — what matters is that the author made
        # an explicit decision rather than inheriting an invisible one).
        if data_schema_path.exists() and _data_schema_has_hidden_fields(data_schema_path):
            if "sse_debug_view" not in payload:
                issues.append(
                    _issue(
                        "error",
                        root,
                        runtime_path,
                        "data.schema.json has x-auto-inject:false fields (hidden state); "
                        "runtime.json must declare sse_debug_view explicitly so the SSE "
                        "debug-view decision is intentional. Set "
                        '"sse_debug_view": {"enabled": false} to keep the secure default, '
                        'or {"enabled": true, "redact_tools": ["data_get", ...]} to opt in '
                        "with the hidden-field accessors masked. See app/models.py "
                        "SseDebugViewConfig.",
                    )
                )


def _verify_activity_contract_files(root: Path, issues: list[VerificationIssue]) -> None:
    for activity_dir in sorted((root / "activities").glob("*")):
        if not activity_dir.is_dir():
            continue
        manifest_path = activity_dir / "manifest.json"
        activity_type_id: str | None = None
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            candidate = manifest.get("activity_type_id") or manifest.get("activity_id")
            if isinstance(candidate, str) and candidate:
                activity_type_id = candidate
        except (OSError, json.JSONDecodeError, AttributeError):
            pass  # manifest errors are reported by _activity_ids

        template_dir = activity_dir / "card_templates"
        if template_dir.exists():
            for template_path in sorted(template_dir.glob("*.json")):
                if template_path.name.endswith(".vars.json"):
                    continue
                vars_path = template_path.with_name(f"{template_path.stem}.vars.json")
                if not vars_path.exists():
                    issues.append(_issue("error", root, vars_path, "card template is missing variables schema"))

        if activity_type_id is None:
            continue
        welcome_path = template_dir / f"{activity_type_id}.welcome.json"
        welcome_vars_path = template_dir / f"{activity_type_id}.welcome.vars.json"
        if not welcome_path.exists():
            issues.append(
                _issue(
                    "error",
                    root,
                    welcome_path,
                    "mandatory static welcome card is missing; dev sync stores this exact card "
                    "for the frontend activity catalog",
                )
            )
            continue

        try:
            welcome = json.loads(welcome_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue  # file-integrity/schema checks report the malformed JSON
        if _contains_welcome_placeholder(welcome):
            issues.append(
                _issue(
                    "error",
                    root,
                    welcome_path,
                    "welcome card cannot contain template placeholders; replace every "
                    "{{variable}} with fixed copy because the card is stored and displayed "
                    "without runtime rendering",
                )
            )

        try:
            welcome_vars = json.loads(welcome_vars_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue  # missing/malformed vars is reported by the existing checks
        if (
            welcome_vars.get("properties") != {}
            or welcome_vars.get("required", []) != []
            or welcome_vars.get("additionalProperties") is not False
        ):
            issues.append(
                _issue(
                    "error",
                    root,
                    welcome_vars_path,
                    "welcome card variables schema must declare no variables: use empty "
                    "properties, no required entries, and additionalProperties=false",
                )
            )


def _contains_welcome_placeholder(value: object) -> bool:
    """Mirror dev-sync's deliberately conservative static-card check."""
    if isinstance(value, str):
        return "{{" in value or "}}" in value
    if isinstance(value, list):
        return any(_contains_welcome_placeholder(item) for item in value)
    if isinstance(value, dict):
        return any(_contains_welcome_placeholder(item) for item in value.values())
    return False


def _verify_generic_runtime_references(root: Path, activity_ids: set[str], issues: list[VerificationIssue]) -> None:
    if not activity_ids:
        return
    for base in GENERIC_ROOTS:
        generic_root = root / base
        if not generic_root.exists():
            continue
        for path in _source_files(generic_root):
            text = _read(path)
            if text is None:
                continue
            for activity_id in sorted(activity_ids):
                if _contains_activity_reference(text, activity_id):
                    issues.append(
                        _issue("error", root, path, f"generic runtime references activity id '{activity_id}'")
                    )


def _verify_frontend_private_state_reads(root: Path, issues: list[VerificationIssue]) -> None:
    frontend_root = root / "frontend-src"
    if not frontend_root.exists():
        return
    for path in _source_files(frontend_root):
        text = _read(path)
        if text is None:
            continue
        if any(pattern.search(text) for pattern in FRONTEND_PRIVATE_STATE_PATTERNS):
            issues.append(_issue("error", root, path, "frontend reads activity-private state"))


# Activity Python must reach LLMs ONLY via ctx.llm (LiteLLM gateway, metered)
# and images/TTS via the platform image_generate / tts_generate tools. Reading
# the runtime settings object (app.settings / get_settings / ctx.llm._settings)
# exposes raw provider keys; calling a provider endpoint directly bypasses the
# gateway + cost-ledger billing. Both are rejected. (Static guard — not a hard
# sandbox; defence-in-depth that catches accidental + obvious bypass at submit
# time. AST-based so comments / docstrings never false-trigger.)
_PROVIDER_KEY_NAMES = {"DEEPSEEK_API_KEY", "DASHSCOPE_API_KEY", "OPENAI_API_KEY"}
_PROVIDER_HOSTS = ("api.deepseek.com", "dashscope.aliyuncs.com")


def _credential_finding(tree: ast.AST) -> str | None:
    """Return a human label for the first credential/provider-bypass pattern in
    real CODE (not comments), else None."""
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and (node.module or "").startswith("app.settings"):
            return "imports app.settings (runtime settings incl. provider keys)"
        if isinstance(node, ast.Import) and any(a.name.startswith("app.settings") for a in node.names):
            return "imports app.settings (runtime settings incl. provider keys)"
        if isinstance(node, ast.Name) and node.id == "get_settings":
            return "calls get_settings() (reads runtime settings incl. provider keys)"
        if isinstance(node, ast.Attribute) and node.attr in {"get_settings", "_settings"}:
            return f"reaches the runtime settings object (.{node.attr})"
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if node.value in _PROVIDER_KEY_NAMES:
                return f"references a provider API-key name ({node.value})"
            if any(h in node.value for h in _PROVIDER_HOSTS):
                return "calls a provider endpoint directly"
    return None


def _verify_no_credential_access(root: Path, issues: list[VerificationIssue]) -> None:
    """Reject activity Python that reaches platform credentials / providers
    directly — that bypasses the LLM gateway + cost-ledger billing. Activities
    get LLM via ``ctx.llm`` (metered) and images/TTS via the platform tools."""
    activities_dir = root / "activities"
    if not activities_dir.exists():
        return
    for activity_dir in sorted(p for p in activities_dir.iterdir() if p.is_dir()):
        for path in _activity_python_files(activity_dir):
            text = _read(path)
            if text is None:
                continue
            try:
                tree = ast.parse(text)
            except SyntaxError:
                continue
            finding = _credential_finding(tree)
            if finding:
                issues.append(
                    _issue(
                        "error",
                        root,
                        path,
                        f"activity code reaches platform credentials/providers directly ({finding}); "
                        "this bypasses LLM-gateway + cost-ledger billing. Use ctx.llm for LLM "
                        "(text/JSON/vision — see references/ctx-llm.md) and the "
                        "image_generate / tts_generate tools for media.",
                    )
                )


def _verify_deepagents_skill_progressive_disclosure(root: Path, issues: list[VerificationIssue]) -> None:
    runner_path = root / "app" / "runner" / "__init__.py"
    text = _read(runner_path)
    if text is None:
        return
    if NON_NATIVE_SKILL_PROMPT_HELPER in text:
        issues.append(_issue("error", root, runner_path, "runtime bypasses DeepAgents progressive skill loading"))
    if re.search(r"glob\([^)]*" + SKILL_MARKDOWN_PATTERN, text) or re.search(
        r"rglob\([^)]*" + SKILL_MARKDOWN_PATTERN, text
    ):
        issues.append(
            _issue("error", root, runner_path, "runtime scans SKILL.md files instead of using DeepAgents skills")
        )
    create_calls = list(re.finditer(r"create_deep_agent\s*\(", text))
    if create_calls and "skills=self._skill_sources(manifest)" not in text:
        issues.append(
            _issue("error", root, runner_path, "create_deep_agent must receive skills=self._skill_sources(manifest)")
        )


# Output-pattern violations: instructive prose in AGENTS.md that describes
# the turn's output as a final JSON payload instead of concrete card-system
# tool calls. Treated as soft warning so AGENTS.md authors can still quote
# these strings in a negated context (e.g. "do NOT write
# `metadata.card_requests`") without tripping the check.
_OUTPUT_PATTERN_VIOLATIONS = (
    "metadata.card_requests",
    "Return one shared `ActivityAgentOutput`",
    "Return exactly one `ActivityAgentOutput`",
)

_NEGATION_TOKENS = ("do not", "don't", "no longer", "never", "do NOT", "DO NOT", "instead of")


def _verify_activity_instruction_shape(root: Path, issues: list[VerificationIssue]) -> None:
    for agents_path in sorted((root / "activities").glob("*/AGENTS.md")):
        text = _read(agents_path) or ""
        line_count = len(text.splitlines())
        if line_count > 80:
            issues.append(
                _issue("warning", root, agents_path, "activity AGENTS.md is large; keep it as a thin skill entrypoint")
            )
        if not re.search(r"skills?/.+SKILL\.md|/activity/skills/", text):
            issues.append(
                _issue("warning", root, agents_path, "activity AGENTS.md does not point clearly to activity skills")
            )
        # Activities run in card-system mode: sub-routes should be described as
        # concrete tool calls, not as a final JSON payload. Skip negations so a
        # doc can still quote these strings to warn against them.
        for line in text.splitlines():
            if any(tok in line.lower() for tok in (t.lower() for t in _NEGATION_TOKENS)):
                continue
            hit = next((p for p in _OUTPUT_PATTERN_VIOLATIONS if p in line), None)
            if hit:
                issues.append(
                    _issue(
                        "warning",
                        root,
                        agents_path,
                        f"AGENTS.md describes output as a final JSON payload ({hit!r}); "
                        "rewrite as concrete card_emit_template / activity-tool calls",
                    )
                )
                break  # one warning per file is enough


def _verify_skill_layering(root: Path, issues: list[VerificationIssue]) -> None:
    skill_entry_name = "SKILL" + ".md"
    for skill_path in sorted((root / "activities").glob(f"*/skills/**/{skill_entry_name}")):
        text = _read(skill_path) or ""
        line_count = len(text.splitlines())
        skill_dir = skill_path.parent
        has_supporting_files = any(
            (skill_dir / name).exists() for name in ("workflows", "policies", "references", "examples", "scripts")
        )
        if not re.search(r"^description:\s*(?:>-\s*)?.{24,}", text, re.MULTILINE):
            issues.append(
                _issue(
                    "warning",
                    root,
                    skill_path,
                    "skill description should clearly state capability and activation conditions",
                )
            )
        if line_count > 120 and not has_supporting_files:
            issues.append(
                _issue(
                    "warning",
                    root,
                    skill_path,
                    "large SKILL.md should move detailed policy into skill-local supporting files",
                )
            )


def _source_files(root: Path) -> list[Path]:
    extensions = {".py", ".js", ".jsx", ".ts", ".tsx", ".json", ".md"}
    return [path for path in sorted(root.rglob("*")) if path.is_file() and path.suffix in extensions]


def _contains_activity_reference(text: str, activity_id: str) -> bool:
    quoted = re.escape(activity_id)
    patterns = (
        rf"activity_id\s*==\s*['\"]{quoted}['\"]",
        rf"activity_id\s*!=\s*['\"]{quoted}['\"]",
        rf"activity_id\s*===\s*['\"]{quoted}['\"]",
        rf"activity_id\s*!==\s*['\"]{quoted}['\"]",
        rf"activityId\([^)]*\)\s*={2, 3}\s*['\"]{quoted}['\"]",
        rf"['\"]{quoted}['\"]\s*={2, 3}\s*activityId\([^)]*\)",
        rf"\bcase\s+['\"]{quoted}['\"]",
        rf"['\"]{quoted}['\"]\s*:",
    )
    return any(re.search(pattern, text) for pattern in patterns)


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def _verify_card_template_field_names(root: Path, issues: list[VerificationIssue]) -> None:
    """Lint card_templates + skill examples for wrong field names.

    Catches the most common ways LLMs produce invalid output by matching
    look-alike field names against the canonical ones in app/models.py:
    - image block must use ``images: [{read_url, title, description}]`` (not ``src/alt/caption``)
    - artifact must use ``url`` (not ``file_url``)
    - artifact ``artifact_id`` must be a non-empty string (pydantic rejects null / missing)
    - image artifact must use ``kind="file"`` (not ``kind="markdown"``)
    """
    targets: list[Path] = []
    for tpl in sorted((root / "activities").glob("*/card_templates/*.json")):
        if not tpl.name.endswith(".vars.json"):
            targets.append(tpl)
    for ex in sorted((root / "activities").glob("*/skills/*/examples/*.json")):
        targets.append(ex)
    for path in targets:
        text = _read(path)
        if text is None:
            continue
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            # other checks already complain about syntactically broken JSON
            continue
        _walk_node_for_field_issues(data, path, root, issues)


def _walk_node_for_field_issues(node, path: Path, root: Path, issues: list[VerificationIssue]) -> None:
    if isinstance(node, dict):
        block_type = node.get("type")
        if isinstance(block_type, str) and block_type in WRONG_BLOCK_FIELDS:
            for bad_field, hint in WRONG_BLOCK_FIELDS[block_type].items():
                if bad_field in node:
                    issues.append(
                        _issue(
                            "error",
                            root,
                            path,
                            f"{block_type} block uses wrong field '{bad_field}' — {hint}",
                        )
                    )
        # Heuristic artifact detection: dict with kind in {markdown, file} and a title
        # (avoids false-positives on FormField etc. which have neither)
        if isinstance(node.get("kind"), str) and node.get("kind") in {"markdown", "file"} and "title" in node:
            for bad_field, hint in WRONG_ARTIFACT_FIELDS.items():
                if bad_field in node:
                    issues.append(
                        _issue(
                            "error",
                            root,
                            path,
                            f"artifact uses wrong field '{bad_field}' — {hint}",
                        )
                    )
            artifact_id = node.get("artifact_id")
            if "artifact_id" not in node or artifact_id is None or artifact_id == "":
                issues.append(
                    _issue(
                        "error",
                        root,
                        path,
                        "artifact is missing artifact_id "
                        "(must be non-empty string; null/missing breaks downstream consumers)",
                    )
                )
            mime = node.get("mime_type", "")
            if (
                node.get("kind") == "markdown"
                and (node.get("url") or node.get("file_url"))
                and isinstance(mime, str)
                and mime.startswith("image/")
            ):
                issues.append(
                    _issue(
                        "error",
                        root,
                        path,
                        "image artifact must use kind='file' (got kind='markdown' with image/* mime type)",
                    )
                )
        for value in node.values():
            _walk_node_for_field_issues(value, path, root, issues)
    elif isinstance(node, list):
        for item in node:
            _walk_node_for_field_issues(item, path, root, issues)


# ── Card-template JSON Schema conformance ────────────────────────────────────
# Full validation of card_templates/*.json against the plugin's canonical
# schemas (schemas/card-template.schema.json + card-vars.schema.json). The
# heuristic field lint above catches look-alike mistakes in prose/examples too,
# but only this pass guarantees a template that passes the verifier will also
# pass the runtime's pydantic OutputCard validation (the "verifier green but
# crashes in prod" class: ImageItem written as url/alt, FormField
# input_type='select', …).
#
# The validator below is a zero-dependency subset of JSON Schema vendored from
# the runtime's app/json_schema.py, adapted for template authoring:
#   * raises ValueError with a "$.card.blocks[1]…" path instead of AppError;
#   * any string containing a "{{var}}" placeholder satisfies ANY schema — a
#     full-string placeholder is substituted verbatim at render time (it may
#     become an array / object / number), so structural checks must treat it
#     as a wildcard;
#   * oneOf branches discriminated by a `type` const (the six block types)
#     report the matching branch's real errors instead of a generic
#     "matched 0 schemas" blob;
#   * supports minProperties/maxProperties (used by card-vars.schema.json).

_TEMPLATE_PLACEHOLDER_RE = re.compile(r"{{\s*[A-Za-z0-9_.-]+\s*}}")
# A *full* placeholder is the entire string — the renderer substitutes the
# variable VALUE verbatim (it may become an array / object / number), so it is a
# true wildcard. Mirrors card_templates.FULL_PLACEHOLDER_RE exactly (no outer
# whitespace tolerance) so the verifier and the renderer agree on which strings
# get verbatim substitution vs str()-interpolation.
_FULL_PLACEHOLDER_RE = re.compile(r"^{{\s*[A-Za-z0-9_.-]+\s*}}$")


def _is_full_placeholder(value: object) -> bool:
    return isinstance(value, str) and _FULL_PLACEHOLDER_RE.match(value) is not None


def _has_embedded_placeholder(value: object) -> bool:
    """A placeholder spliced into surrounding text (or alongside others). The
    renderer str()-interpolates these, so the rendered value is ALWAYS a string —
    it's only valid where a string is allowed, but its content is unknown."""
    return (
        isinstance(value, str)
        and not _is_full_placeholder(value)
        and _TEMPLATE_PLACEHOLDER_RE.search(value) is not None
    )


def _resolve_local_ref(root_schema: dict, ref: str) -> dict | bool:
    if not isinstance(ref, str) or not ref.startswith("#/"):
        raise ValueError(f"unsupported $ref {ref!r}; only local '#/…' refs are supported")
    current = root_schema
    for raw_part in ref[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(current, dict) or part not in current:
            raise ValueError(f"unresolved $ref {ref!r}")
        current = current[part]
    return current


def _schema_type_matches(value, expected: str) -> bool:
    if expected == "object":
        return isinstance(value, dict)
    if expected == "array":
        return isinstance(value, list)
    if expected == "string":
        return isinstance(value, str)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "null":
        return value is None
    return True


def _schema_check(value, schema, *, root_schema: dict, path: str, refs: tuple = ()) -> None:
    """Validate ``value`` against ``schema`` (subset of JSON Schema draft
    2020-12); raise ValueError with an instance path on the first failure."""
    if schema is True or schema == {}:
        return
    if schema is False:
        raise ValueError(f"{path}: value is not allowed")
    if not isinstance(schema, dict):
        raise ValueError(f"{path}: schema must be an object")
    if _is_full_placeholder(value):
        return  # whole-string placeholder → value substituted verbatim, any shape
    # An embedded placeholder ("prefix {{x}}") renders to a STRING, so its TYPE
    # is checked below (this is what catches e.g. `blocks: "see {{blocks}}"` where
    # an array is required) but its CONTENT constraints (const/enum/length/pattern)
    # are skipped — the rendered text isn't known at authoring time.
    embedded = _has_embedded_placeholder(value)
    if "$ref" in schema:
        ref = schema["$ref"]
        if ref in refs:
            raise ValueError(f"{path}: recursive $ref {ref!r} is not supported")
        _schema_check(
            value, _resolve_local_ref(root_schema, ref), root_schema=root_schema, path=path, refs=(*refs, ref)
        )
    if "const" in schema and not embedded and value != schema["const"]:
        raise ValueError(f"{path}: expected const {schema['const']!r}, got {value!r}")
    if "enum" in schema and not embedded and value not in schema["enum"]:
        raise ValueError(f"{path}: expected one of {schema['enum']!r}, got {value!r}")
    if "allOf" in schema:
        for option in schema["allOf"]:
            _schema_check(value, option, root_schema=root_schema, path=path, refs=refs)
    if "oneOf" in schema:
        _schema_check_one_of(value, schema["oneOf"], root_schema=root_schema, path=path, refs=refs)
    if "anyOf" in schema:
        errors: list[str] = []
        for option in schema["anyOf"]:
            try:
                _schema_check(value, option, root_schema=root_schema, path=path, refs=refs)
                break
            except ValueError as exc:
                errors.append(str(exc))
        else:
            raise ValueError(f"{path}: no anyOf branch matched; first errors: {errors[:2]}")

    expected_type = schema.get("type")
    if isinstance(expected_type, list):
        if not any(_schema_type_matches(value, item) for item in expected_type):
            raise ValueError(f"{path}: expected type {expected_type!r}, got {type(value).__name__}")
    elif isinstance(expected_type, str) and not _schema_type_matches(value, expected_type):
        raise ValueError(f"{path}: expected type {expected_type!r}, got {type(value).__name__}")

    if isinstance(value, dict):
        for key in schema.get("required", []):
            if key not in value:
                raise ValueError(f"{path}.{key}: required property is missing")
        properties = schema.get("properties", {})
        if not isinstance(properties, dict):
            properties = {}
        for key, subschema in properties.items():
            if key in value:
                _schema_check(value[key], subschema, root_schema=root_schema, path=f"{path}.{key}", refs=refs)
        additional = schema.get("additionalProperties", True)
        extra_keys = sorted(set(value) - set(properties))
        if additional is False and extra_keys:
            raise ValueError(f"{path}: unexpected properties {extra_keys!r}")
        if isinstance(additional, dict):
            for key in extra_keys:
                _schema_check(value[key], additional, root_schema=root_schema, path=f"{path}.{key}", refs=refs)
        min_props = schema.get("minProperties")
        if isinstance(min_props, int) and len(value) < min_props:
            raise ValueError(f"{path}: expected at least {min_props} properties")
        max_props = schema.get("maxProperties")
        if isinstance(max_props, int) and len(value) > max_props:
            raise ValueError(f"{path}: expected at most {max_props} properties")

    if isinstance(value, list):
        min_items = schema.get("minItems")
        if isinstance(min_items, int) and len(value) < min_items:
            raise ValueError(f"{path}: expected at least {min_items} items")
        max_items = schema.get("maxItems")
        if isinstance(max_items, int) and len(value) > max_items:
            raise ValueError(f"{path}: expected at most {max_items} items")
        items_schema = schema.get("items")
        if isinstance(items_schema, (dict, bool)):
            for index, item in enumerate(value):
                _schema_check(item, items_schema, root_schema=root_schema, path=f"{path}[{index}]", refs=refs)

    if isinstance(value, str) and not embedded:
        min_length = schema.get("minLength")
        if isinstance(min_length, int) and len(value) < min_length:
            raise ValueError(f"{path}: expected string length >= {min_length}")
        max_length = schema.get("maxLength")
        if isinstance(max_length, int) and len(value) > max_length:
            raise ValueError(f"{path}: expected string length <= {max_length}")
        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.search(pattern, value) is None:
            raise ValueError(f"{path}: expected string to match pattern {pattern!r}")

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        minimum = schema.get("minimum")
        if isinstance(minimum, (int, float)) and value < minimum:
            raise ValueError(f"{path}: expected number >= {minimum}")
        maximum = schema.get("maximum")
        if isinstance(maximum, (int, float)) and value > maximum:
            raise ValueError(f"{path}: expected number <= {maximum}")


def _schema_check_one_of(value, options: list, *, root_schema: dict, path: str, refs: tuple) -> None:
    """oneOf with a fast path for const-discriminated unions (block types):
    when every branch fixes ``properties.type.const`` and the instance has a
    ``type`` key, validate against the matching branch only — its errors are
    the actionable ones ("images[0]: unexpected properties ['alt']"), not
    "matched 0 of 6 schemas"."""
    resolved: list = []
    for option in options:
        if isinstance(option, dict) and "$ref" in option:
            resolved.append(_resolve_local_ref(root_schema, option["$ref"]))
        else:
            resolved.append(option)
    discriminated = (
        isinstance(value, dict)
        and "type" in value
        and all(
            isinstance(o, dict)
            and isinstance(o.get("properties", {}).get("type"), dict)
            and "const" in o["properties"]["type"]
            for o in resolved
        )
    )
    if discriminated:
        for branch in resolved:
            if branch["properties"]["type"]["const"] == value.get("type"):
                _schema_check(value, branch, root_schema=root_schema, path=path, refs=refs)
                return
        allowed = sorted(o["properties"]["type"]["const"] for o in resolved)
        raise ValueError(f"{path}.type: unknown block type {value.get('type')!r}; expected one of {allowed}")
    matches = 0
    errors: list[str] = []
    for option in options:
        try:
            _schema_check(value, option, root_schema=root_schema, path=path, refs=refs)
            matches += 1
        except ValueError as exc:
            errors.append(str(exc))
    if matches != 1:
        raise ValueError(f"{path}: expected exactly one matching schema; matched {matches}; first errors: {errors[:2]}")


def _load_plugin_schema(name: str) -> dict | None:
    """Load a schema shipped with this plugin (…/schemas/<name>), or None when
    the file is missing/unreadable (unusual install layout)."""
    path = Path(__file__).resolve().parent.parent / "schemas" / name
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return payload if isinstance(payload, dict) else None


def _verify_card_template_schema_conformance(root: Path, issues: list[VerificationIssue]) -> None:
    """Validate every card_templates/*.json against card-template.schema.json
    and every *.vars.json against card-vars.schema.json (both shipped in this
    plugin's schemas/). Errors here reproduce 1:1 as runtime OutputCard
    validation failures, so severity is error."""
    template_schema = _load_plugin_schema("card-template.schema.json")
    vars_schema = _load_plugin_schema("card-vars.schema.json")
    if template_schema is None and vars_schema is None:
        return  # schemas not shipped alongside this copy; heuristic lint above still applies
    for path in sorted((root / "activities").glob("*/card_templates/*.json")):
        text = _read(path)
        if text is None:
            continue
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            issues.append(_issue("error", root, path, f"card template file is not valid JSON: {exc}"))
            continue
        is_vars = path.name.endswith(".vars.json")
        schema = vars_schema if is_vars else template_schema
        if schema is None:
            continue
        schema_name = "card-vars.schema.json" if is_vars else "card-template.schema.json"
        consequence = (
            "card_emit_template rejects variables against a malformed vars schema"
            if is_vars
            else "this exact shape is rejected by the runtime's OutputCard validation at emit time"
        )
        try:
            _schema_check(data, schema, root_schema=schema, path="$")
        except ValueError as exc:
            issues.append(
                _issue(
                    "error",
                    root,
                    path,
                    f"fails {schema_name}: {exc} — {consequence} (see references/card-block-types.md)",
                )
            )


def _canon_pkg(name: str) -> str:
    """PEP 503 style normalization so import names and distribution names
    compare equal across the ``-`` / ``_`` / ``.`` and case differences
    (``graphiti_core`` ↔ ``graphiti-core``, ``Jinja2`` ↔ ``jinja2``)."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def _load_python_baseline() -> set[str] | None:
    """Top-level import names the platform itself provides (see
    _PYTHON_BASELINE_PATH). Returns None if the baseline file is absent so the
    caller can skip the check rather than flood false positives."""
    text = _read(_PYTHON_BASELINE_PATH)
    if text is None:
        return None
    names: set[str] = set()
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            names.add(line)
    return names


def _parse_requirements_dists(req_path: Path) -> set[str]:
    """Canonical distribution names declared in an activity requirements.txt."""
    text = _read(req_path)
    if text is None:
        return set()
    dists: set[str] = set()
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        # Strip everything after the first extras bracket / version specifier /
        # marker / url. Leaves the bare distribution name.
        m = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", line)
        if m:
            dists.add(_canon_pkg(m.group(0)))
    return dists


def _activity_local_modules(activity_dir: Path) -> set[str]:
    """Names importable as modules shipped inside the activity, at any depth —
    helper modules (``_graph.py``), sub-packages, and skill ``scripts/``
    siblings imported after a ``sys.path`` insert (e.g. bedtime-story's
    ``from tavily_search import ...``). These are not third-party. A shipped
    file shadows a same-named third-party package at runtime anyway, so folding
    every shipped stem in is consistent with how the import resolves."""
    names: set[str] = set()
    for path in activity_dir.rglob("*.py"):
        rel = path.relative_to(activity_dir).as_posix()
        if "__pycache__" in rel:
            continue
        names.add(path.stem)
        if path.name == "__init__.py":
            names.add(path.parent.name)
    return names


def _activity_python_files(activity_dir: Path) -> list[Path]:
    """Runtime Python files shipped by the activity. Excludes the frontend
    project (``site/``), bytecode caches, and tests (not loaded at runtime)."""
    out: list[Path] = []
    for path in sorted(activity_dir.rglob("*.py")):
        rel = path.relative_to(activity_dir).as_posix()
        if rel.startswith("site/") or "/site/" in rel:
            continue
        if "__pycache__" in rel:
            continue
        if rel.startswith("tests/") or "/tests/" in rel:
            continue
        if path.name.startswith("test_") or path.name.endswith("_test.py") or path.name == "conftest.py":
            continue
        out.append(path)
    return out


def _top_level_imports(tree: ast.AST) -> set[str]:
    """Top-level package names of absolute imports. Relative imports
    (``from . import x``) are skipped — they are handled by a separate rule."""
    tops: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                tops.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:
                tops.add(node.module.split(".")[0])
    return tops


def _installed_dists_for_import(import_name: str) -> set[str]:
    """Canonical distribution names that provide ``import_name`` in the
    verifier's own environment, for resolving non-canonical aliases like
    ``PIL`` → ``pillow``. Best-effort: empty if the package isn't installed."""
    try:
        import importlib.metadata as _im

        return {_canon_pkg(d) for d in _im.packages_distributions().get(import_name, [])}
    except Exception:  # noqa: BLE001 — metadata access is best-effort
        return set()


def _verify_python_dependencies(root: Path, issues: list[VerificationIssue]) -> None:
    """Every third-party package an activity imports must be declared in its
    own requirements.txt (the runtime shares one venv across activities; see
    _PYTHON_BASELINE_PATH note). Flags undeclared imports as errors."""
    activity_dirs = [p for p in sorted((root / "activities").glob("*")) if p.is_dir()]
    if not activity_dirs:
        return

    baseline = _load_python_baseline()
    if baseline is None:
        issues.append(
            _issue(
                "warning",
                root,
                _PYTHON_BASELINE_PATH,
                "python baseline not found — skipping the undeclared-dependency check. "
                "Generate it with tools/gen-python-baseline.py from the host venv.",
            )
        )
        return

    stdlib = set(sys.stdlib_module_names)

    for activity_dir in activity_dirs:
        py_files = _activity_python_files(activity_dir)
        if not py_files:
            continue
        declared = _parse_requirements_dists(activity_dir / "requirements.txt")
        local = _activity_local_modules(activity_dir)
        # import name -> first file that triggered it (for a precise message)
        undeclared: dict[str, Path] = {}
        for path in py_files:
            source = _read(path)
            if source is None:
                continue
            try:
                tree = ast.parse(source, filename=str(path))
            except SyntaxError:
                continue  # syntax errors are reported by the module-specific checks
            for imp in _top_level_imports(tree):
                if imp in stdlib or imp in FIRST_PARTY_ROOTS or imp in local or imp in baseline:
                    continue
                canon = _canon_pkg(imp)
                if canon in declared:
                    continue
                installed = _installed_dists_for_import(imp)
                if installed & declared or any(_canon_pkg_in(d, baseline) for d in installed):
                    continue
                undeclared.setdefault(imp, path)

        for imp, path in sorted(undeclared.items()):
            issues.append(
                _issue(
                    "error",
                    root,
                    path,
                    f"imports third-party package '{imp}' but it is not declared in "
                    f"activities/{activity_dir.name}/requirements.txt (and is not stdlib "
                    f"nor provided by the platform baseline). The runtime shares one venv "
                    f"across activities, so undeclared imports ImportError on a fresh host. "
                    f"Add a pinned line to requirements.txt for the distribution that "
                    f"provides '{imp}' (usually the same name, e.g. '{imp}==<version>'; for "
                    f"aliases use the distribution name, e.g. 'opencv-python' for 'cv2', "
                    f"'pillow' for 'PIL'), or — if it really is a platform dependency — "
                    f"regenerate the baseline with tools/gen-python-baseline.py.",
                )
            )


def _canon_pkg_in(dist_canon: str, baseline: set[str]) -> bool:
    """True if a distribution maps to an import name already in the baseline.
    Distribution names and import names mostly coincide after canonicalization
    (``-``/``_`` folded); this catches the leftover alias cases."""
    folded = dist_canon.replace("-", "_")
    return folded in baseline or dist_canon in baseline


def _issue(severity: Severity, root: Path, path: Path, message: str) -> VerificationIssue:
    try:
        rendered = path.relative_to(root).as_posix()
    except ValueError:
        rendered = path.as_posix()
    return VerificationIssue(severity=severity, path=rendered, message=message)


# ─── Static Preview contracts (§7.3 in design doc) ──────────────────────────


def _verify_static_preview_contracts(root: Path, issues: list[VerificationIssue]) -> None:
    """Validate the manifest fields + Python modules introduced by the
    Static Preview model.

    Seven rules for activity tool modules:

      1. ``tools_module`` exists → ``<module>.py`` must exist AND define
         ``make_tools`` at module level.
      2. ``dsl_builder_module`` exists → ``<module>.py`` must exist AND
         define ``build`` at module level.
      3. ``@tool`` names inside ``make_tools`` must not collide with
         ``BUILTIN_TOOL_NAMES``. AST-walk the decorators; string-literal
         first arg is the tool name.
      4. ``dsl_builder_module`` set → ``activities/<id>/site/`` must
         exist (the SPA target; ``site/dist/`` can be missing — build
         happens at install time).
      5. ``data.schema.json`` (if present) must have a top-level
         ``default`` field. Current data_store.initialize_data_store
         only reads top-level default; ``properties.*.default`` is
         silently ignored.
      6. ``tools.py`` must not use ``from .xxx`` relative imports —
         spec_from_file_location single-file loading has no package
         context and these raise ImportError at runtime.
    """
    for manifest_path in sorted((root / "activities").glob("*/manifest.json")):
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            # Already reported by _activity_ids.
            continue

        activity_dir = manifest_path.parent
        tools_module = payload.get("tools_module")
        dsl_builder_module = payload.get("dsl_builder_module")
        # Rule 1 & 6: tools_module → tools.py exists + has make_tools + no relative imports
        if isinstance(tools_module, str) and tools_module:
            _verify_tools_module(root, activity_dir, tools_module, issues)

        # Rule 2: dsl_builder_module → builder file exists + exports build
        if isinstance(dsl_builder_module, str) and dsl_builder_module:
            _verify_dsl_builder_module(root, activity_dir, dsl_builder_module, issues)

        # Rule 4: dsl_builder_module → site/ dir exists
        if isinstance(dsl_builder_module, str) and dsl_builder_module:
            site_dir = activity_dir / "site"
            if not site_dir.is_dir():
                issues.append(
                    _issue(
                        "error",
                        root,
                        manifest_path,
                        f"activity declares dsl_builder_module='{dsl_builder_module}' "
                        f"but {site_dir.relative_to(root)} is missing; the Static "
                        f"Preview model needs the site/ frontend project (run "
                        f"tools/derive-frontend.sh to scaffold it)",
                    )
                )

        # Rule 5: data.schema.json (if present) needs top-level default
        data_schema_path = activity_dir / "data.schema.json"
        if data_schema_path.exists():
            _verify_data_schema_top_level_default(root, data_schema_path, issues)


def _verify_frontend_file_dependencies(root: Path, issues: list[VerificationIssue]) -> None:
    """Activity frontends must be self-contained when using npm ``file:`` deps.

    The runtime sync API uploads only the activity directory. A dependency like
    ``file:../../../packages/foo`` works inside the monorepo but fails on a
    remote runtime, so every ``file:`` target must resolve inside the activity
    directory itself (for example ``file:vendor/foo``).
    """
    sections = ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies")
    for package_path in sorted((root / "activities").glob("*/site/package.json")):
        activity_dir = package_path.parents[1]
        site_dir = package_path.parent
        try:
            payload = json.loads(package_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            issues.append(_issue("error", root, package_path, f"site/package.json is unreadable: {exc}"))
            continue
        if not isinstance(payload, dict):
            issues.append(_issue("error", root, package_path, "site/package.json must be a JSON object"))
            continue
        for section in sections:
            deps = payload.get(section)
            if deps is None:
                continue
            if not isinstance(deps, dict):
                issues.append(_issue("error", root, package_path, f"site/package.json {section} must be an object"))
                continue
            for name, spec in sorted(deps.items()):
                if not isinstance(spec, str) or not spec.startswith("file:"):
                    continue
                target_text = spec[len("file:") :]
                target_path = Path(target_text)
                if target_path.is_absolute():
                    issues.append(
                        _issue(
                            "error",
                            root,
                            package_path,
                            f"frontend file: dependency {name!r} uses absolute path {target_text!r}; "
                            "vendor it inside the activity directory instead",
                        )
                    )
                    continue
                raw_target = site_dir / target_path
                try:
                    resolved_activity = activity_dir.resolve(strict=True)
                    resolved_target = raw_target.resolve(strict=True)
                except OSError:
                    issues.append(
                        _issue(
                            "error",
                            root,
                            package_path,
                            f"frontend file: dependency {name!r} target {target_text!r} does not exist",
                        )
                    )
                    continue
                if not _is_relative_to(resolved_target, resolved_activity):
                    issues.append(
                        _issue(
                            "error",
                            root,
                            package_path,
                            f"frontend file: dependency {name!r} target {target_text!r} escapes activity directory; "
                            "use an activity-local vendor path such as file:vendor/<package>",
                        )
                    )


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def _verify_tools_module(
    root: Path,
    activity_dir: Path,
    tools_module: str,
    issues: list[VerificationIssue],
) -> None:
    """Rule 1 + 3 + 7 for tools.py."""
    path = activity_dir / f"{tools_module}.py"
    if not path.exists():
        issues.append(
            _issue(
                "error",
                root,
                activity_dir / "manifest.json",
                f"manifest declares tools_module='{tools_module}' but "
                f"{path.relative_to(root)} not found — create it with "
                f"`def make_tools(ctx): ...` returning a list of @tool callables",
            )
        )
        return

    source = _read(path)
    if source is None:
        return

    # Rule 7: relative imports
    for line_no, line in enumerate(source.splitlines(), start=1):
        stripped = line.lstrip()
        # ``from .`` (package-relative). ``import .`` is invalid Python.
        if stripped.startswith("from ."):
            issues.append(
                _issue(
                    "error",
                    root,
                    path,
                    f"line {line_no}: relative imports are not supported in activity "
                    f"tools.py (spec_from_file_location has no package context). "
                    f"Either keep tools.py self-contained or import from app.* / "
                    f"langchain_core.* / standard library.",
                )
            )

    # Parse AST for rules 1 and 3.
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        issues.append(
            _issue(
                "error",
                root,
                path,
                f"tools.py has a syntax error at line {exc.lineno}: {exc.msg}",
            )
        )
        return

    make_tools_fn: ast.FunctionDef | None = None
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "make_tools":
            make_tools_fn = node
            break
    if make_tools_fn is None:
        issues.append(
            _issue(
                "error",
                root,
                path,
                "tools.py must export `make_tools(ctx)` at module level (returning a list of @tool callables)",
            )
        )
        return

    # Rule 3: walk inner functions and collect @tool("name") declarations.
    for inner in ast.walk(make_tools_fn):
        if not isinstance(inner, ast.FunctionDef):
            continue
        for deco in inner.decorator_list:
            tool_name = _extract_tool_decorator_name(deco)
            if tool_name is None:
                continue
            if tool_name in BUILTIN_TOOL_NAMES:
                issues.append(
                    _issue(
                        "error",
                        root,
                        path,
                        f"activity tool '{tool_name}' (line {inner.lineno}) conflicts "
                        f"with a runtime builtin — rename it. Reserved names include: "
                        f"data_set / card_emit / image_generate / execute / read_file / "
                        f"task / write_todos (full list in BUILTIN_TOOL_NAMES).",
                    )
                )


def _extract_tool_decorator_name(deco: ast.expr) -> str | None:
    """Pull the literal name from ``@tool("the_name", ...)``.

    Recognises ``@tool("name")`` and ``@tool("name", parse_docstring=True)``;
    plain ``@tool`` without a name string is ignored (rare; not the
    pattern activities are expected to use).
    """
    if not isinstance(deco, ast.Call):
        return None
    func = deco.func
    fn_name = func.id if isinstance(func, ast.Name) else func.attr if isinstance(func, ast.Attribute) else None
    if fn_name != "tool":
        return None
    if not deco.args:
        return None
    first = deco.args[0]
    if isinstance(first, ast.Constant) and isinstance(first.value, str):
        return first.value
    return None


def _collect_make_tools_names(path: Path) -> set[str]:
    """AST-extract the @tool("name") names declared inside make_tools().

    Same extraction _verify_tools_module uses for the builtin-collision
    check, returned as a set so doc-reference verification can diff against
    it. Returns an empty set if the file is unreadable or unparsable
    (those failures are surfaced elsewhere).
    """
    source = _read(path)
    if source is None:
        return set()
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return set()
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "make_tools":
            for inner in ast.walk(node):
                if isinstance(inner, ast.FunctionDef):
                    for deco in inner.decorator_list:
                        tool_name = _extract_tool_decorator_name(deco)
                        if tool_name:
                            names.add(tool_name)
    return names


# A keyword argument inside a documented call: ``name=`` but not ``name==`` (a
# comparison) and not ``>=`` / ``<=`` / ``!=`` (the char before ``=`` is a word
# char we already captured, so only equality with a second ``=`` needs guarding).
_DOC_KWARG_RE = re.compile(r"\b([a-zA-Z_][a-zA-Z0-9_]*)\s*=(?!=)")


def _collect_make_tools_signatures(path: Path) -> dict[str, set[str] | None]:
    """Map each ``@tool("name")`` to the set of its parameter names.

    A value of ``None`` means "accept any kwarg" — the tool takes ``**kwargs``
    so we cannot meaningfully check argument names against it. Used by the
    doc-reference check to catch documented calls that pass a kwarg the tool's
    signature does not declare (strict tool-call mode rejects unknown args at
    runtime, so the LLM's call fails).
    """
    source = _read(path)
    if source is None:
        return {}
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return {}
    sigs: dict[str, set[str] | None] = {}
    for node in tree.body:
        if not (isinstance(node, ast.FunctionDef) and node.name == "make_tools"):
            continue
        for inner in ast.walk(node):
            if not isinstance(inner, ast.FunctionDef):
                continue
            tool_name = next(
                (name for deco in inner.decorator_list if (name := _extract_tool_decorator_name(deco))),
                None,
            )
            if not tool_name:
                continue
            a = inner.args
            if a.kwarg is not None:  # **kwargs → any keyword accepted
                sigs[tool_name] = None
                continue
            params: set[str] = set()
            for arg in (*a.posonlyargs, *a.args, *a.kwonlyargs):
                if arg.arg != "self":
                    params.add(arg.arg)
            sigs[tool_name] = params
    return sigs


def _verify_doc_tool_references(root: Path, issues: list[VerificationIssue]) -> None:
    """Flag tools referenced with call syntax in an activity's docs that
    its tools.py does not export.

    Catches the recurring "docs name a tool the code doesn't have" drift
    (e.g. tiger-commentator once documented a generate_tiger_avatar tool
    that did not exist). The LLM reads the doc, calls the missing tool,
    gets an error, and retries — burning tokens.

    Scope and deliberate limitations:
      * Direction is doc→code only. Tools that exist in code but are
        undocumented are NOT reported — low value, high noise.
      * Only call-syntax references (`tool_name(`) are checked, since
        that is the unambiguous "the LLM should call this" signal. Bare
        backtick mentions in tool-overview tables or prose are ignored to
        keep the check precise (near-zero false positives).
      * Builtins (BUILTIN_TOOL_NAMES) and known framework entrypoints
        (_DOC_NON_TOOL_CALLS) are never flagged.
    Severity is WARNING — drift should be fixed but must not block an
    activity from loading.
    """
    for manifest_path in sorted((root / "activities").glob("*/manifest.json")):
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            # Already reported by _activity_ids.
            continue
        tools_module = payload.get("tools_module")
        if not (isinstance(tools_module, str) and tools_module):
            continue
        activity_dir = manifest_path.parent
        tools_path = activity_dir / f"{tools_module}.py"
        if not tools_path.exists():
            # Missing tools.py already reported by _verify_tools_module.
            continue
        actual = _collect_make_tools_names(tools_path)
        signatures = _collect_make_tools_signatures(tools_path)
        known = actual | BUILTIN_TOOL_NAMES | _DOC_NON_TOOL_CALLS

        doc_paths: list[Path] = []
        agents_md = activity_dir / "AGENTS.md"
        if agents_md.exists():
            doc_paths.append(agents_md)
        doc_paths.extend(sorted(activity_dir.glob("skills/**/*.md")))

        for doc_path in doc_paths:
            text = _read(doc_path) or ""
            mentioned = set(_DOC_TOOL_CALL_RE.findall(text))
            missing = mentioned - known
            if missing:
                issues.append(
                    _issue(
                        "warning",
                        root,
                        doc_path,
                        f"doc calls tool(s) not exported by {tools_module}.py make_tools(): "
                        f"{sorted(missing)} — a tool was renamed/removed or the doc has a "
                        f"typo; the LLM will call a nonexistent tool and get an error",
                    )
                )
            _verify_doc_tool_kwargs(text, signatures, doc_path, root, issues)


def _verify_doc_tool_kwargs(
    text: str,
    signatures: dict[str, set[str] | None],
    doc_path: Path,
    root: Path,
    issues: list[VerificationIssue],
) -> None:
    r"""Flag documented ``activity_tool(kwarg=...)`` calls that pass a keyword
    the tool's signature doesn't declare.

    Only ACTIVITY tools are checked (we have their real AST signature); the call
    is matched single-line with no nested parens (``\bNAME\(([^()\n]*)\)``) so
    prose / multi-line examples that we can't parse cleanly are skipped rather
    than guessed at — keeping this as close to zero-false-positive as the parent
    tool-name check. Tools taking ``**kwargs`` (signature None) are skipped.
    Severity WARNING, matching the parent check.
    """
    for tool_name, params in signatures.items():
        if params is None:  # **kwargs — any keyword is valid
            continue
        for call in re.finditer(rf"\b{re.escape(tool_name)}\(([^()\n]*)\)", text):
            kwargs = set(_DOC_KWARG_RE.findall(call.group(1)))
            unknown = sorted(kwargs - params)
            if unknown:
                issues.append(
                    _issue(
                        "warning",
                        root,
                        doc_path,
                        f"doc calls {tool_name}({', '.join(f'{k}=...' for k in unknown)}) but "
                        f"{tool_name}'s signature has no such parameter(s) — strict tool-call mode "
                        f"rejects unknown args at runtime; fix the doc or the tool signature "
                        f"(valid params: {sorted(params) or 'none'})",
                    )
                )


def _verify_dsl_builder_module(
    root: Path,
    activity_dir: Path,
    module: str,
    issues: list[VerificationIssue],
) -> None:
    """Rule 2 for dsl_builder.py — file must exist + define ``build``."""
    path = activity_dir / f"{module}.py"
    if not path.exists():
        issues.append(
            _issue(
                "error",
                root,
                activity_dir / "manifest.json",
                f"manifest declares dsl_builder_module='{module}' but "
                f"{path.relative_to(root)} not found — create it with "
                f"`def build(instance_dir): ...` returning the DSL dict your activity's SPA consumes",
            )
        )
        return

    source = _read(path)
    if source is None:
        return
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        issues.append(
            _issue(
                "error",
                root,
                path,
                f"dsl_builder.py has a syntax error at line {exc.lineno}: {exc.msg}",
            )
        )
        return

    has_build = any(isinstance(n, ast.FunctionDef) and n.name == "build" for n in tree.body)
    if not has_build:
        issues.append(
            _issue(
                "error",
                root,
                path,
                "dsl_builder.py must export `build(instance_dir)` at module level "
                "(returning the DSL dict your activity's SPA consumes)",
            )
        )


def _verify_data_schema_top_level_default(
    root: Path,
    schema_path: Path,
    issues: list[VerificationIssue],
) -> None:
    """Rule 5: data.schema.json must define a top-level ``default``.

    Without it, ``initialize_data_store`` seeds with ``{}`` and the
    activity loses the keys it expected to find on first read.
    ``properties.*.default`` does NOT count — the data store only
    consumes the top-level field.
    """
    try:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        issues.append(
            _issue(
                "error",
                root,
                schema_path,
                f"data.schema.json is unreadable: {exc}",
            )
        )
        return
    if not isinstance(schema, dict):
        issues.append(
            _issue(
                "error",
                root,
                schema_path,
                "data.schema.json must be an object schema",
            )
        )
        return
    if "default" not in schema:
        issues.append(
            _issue(
                "error",
                root,
                schema_path,
                "data.schema.json must define a top-level `default` object. The "
                "data store only reads the top-level default — `properties.*.default` "
                "is silently ignored, leaving the activity with `{}` on first read.",
            )
        )


def main() -> int:
    # External developers may run this on an old interpreter — the repo's ruff
    # target (3.10+) sees this as an outdated version block, but here it's the
    # live path that turns a mid-run AttributeError (sys.stdlib_module_names
    # is 3.10+) into a clear version error.
    if sys.version_info < (3, 10):  # noqa: UP036
        print(
            f"activity_verifier.py requires Python >= 3.10 (found {sys.version_info.major}.{sys.version_info.minor}).",
            file=sys.stderr,
        )
        return 2
    parser = argparse.ArgumentParser(description="Verify DeepAgents activity runtime boundaries.")
    parser.add_argument("root", nargs="?", default=".", help="Project root to verify.")
    args = parser.parse_args()

    root = Path(args.root)
    issues = verify_project(root)
    for issue in issues:
        print(f"{issue.severity.upper()} {issue.path}: {issue.message}")

    # A clean run prints nothing but "scanned N activities", so a wrong CWD that
    # finds zero activities can't masquerade as a pass. Count manifests under
    # <root>/activities (the only place verify_project looks).
    scanned = len(list((root / "activities").glob("*/manifest.json")))
    if scanned == 0:
        print(
            f"WARNING: no activities found under {root}/activities — "
            "nothing was verified. Run from your project root, or pass it as the "
            "first argument: `activity_verifier.py <project-root>`.",
            file=sys.stderr,
        )
        return 2
    error_count = sum(1 for i in issues if i.severity == "error")
    warn_count = len(issues) - error_count
    print(f"scanned {scanned} activit{'y' if scanned == 1 else 'ies'}: {error_count} ERROR, {warn_count} WARNING")
    return 1 if error_count else 0


if __name__ == "__main__":
    raise SystemExit(main())
